spring:
  jpa:
    database-platform: org.hibernate.dialect.PGDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/adventure
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
